project_id = "mwzohmvzgcyxqjctmyrr"

[functions.send-payment-notification]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = false

[functions.send-delivery-notification]
verify_jwt = false

[functions.send-cancellation-notification]
verify_jwt = false

[functions.send-refund-notification]
verify_jwt = false

[functions.send-review-notification]
verify_jwt = false

[functions.send-admin-order-notification]
verify_jwt = false

[functions.digiseller-payment]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.digiseller-webhook]
verify_jwt = false
