project_id = "mwzohmvzgcyxqjctmyrr"

[functions.send-payment-notification]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = false

[functions.send-delivery-notification]
verify_jwt = false
